language: ruby
sudo: false
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - CODECLIMATE_REPO_TOKEN=3f97bb5305cd65f6683587a32b4b3eae42cfec26d3de56374b10b3efb78ccf6a bundle exec rspec
  - bundle exec codeclimate-test-reporter
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
